/**
 * run-with-enforcer.ts
 *
 * Integration test helper. Spawns a child Node.js process that:
 *
 *  1. Loads the enforcer via --require (TypeScript via ts-node)
 *  2. Runs inside a temp directory containing:
 *      - package-capabilities.json (determines what each package is allowed)
 *      - node_modules/<pkgName>/index.js (fixture files copied here so that
 *        getCallerPackage() correctly identifies them as npm packages)
 *      - test-script.js (the script that exercises the fixture)
 *
 * WHY fixtures go in node_modules:
 *   The enforcer identifies a package by looking for 'node_modules' in the
 *   require() caller's file path. Requiring a fixture from an absolute path
 *   like /project/test/fixtures/malicious-fs makes it look like user code
 *   (null caller = unrestricted). Placing fixtures inside node_modules makes
 *   the enforcer treat them as third-party packages and apply their profile.
 */

import { execSync } from 'child_process'
import fs from 'fs'
import os from 'os'
import path from 'path'
import type { CapabilitiesFile } from '../../src/capabilities/schema'

export interface RunResult {
  exitCode: number
  stdout: string
  stderr: string
}

const PROJECT_ROOT = path.resolve(__dirname, '../..')
const ENFORCER_PATH = path.resolve(PROJECT_ROOT, 'src/enforcer/index.ts')
const TS_CONFIG_PATH = path.resolve(PROJECT_ROOT, 'tsconfig.json')
const PROJECT_NODE_MODULES = path.resolve(PROJECT_ROOT, 'node_modules')

// Verify critical paths exist at startup to get early feedback
if (!fs.existsSync(ENFORCER_PATH)) throw new Error(`[run-with-enforcer] enforcer not found: ${ENFORCER_PATH}`)
if (!fs.existsSync(TS_CONFIG_PATH)) throw new Error(`[run-with-enforcer] tsconfig not found: ${TS_CONFIG_PATH}`)

/**
 * Runs a script in a temporary directory with the enforcer active.
 *
 * @param scriptContent   JavaScript to execute (CommonJS)
 * @param capabilities    Contents of package-capabilities.json for this test
 * @param fixtures        Map of pkgName → fixture source directory to copy into node_modules
 * @param extraEnv        Additional environment variables for the child process
 */
export function runWithEnforcer(
  scriptContent: string,
  capabilities: CapabilitiesFile,
  fixtures: Record<string, string> = {},
  extraEnv: Record<string, string> = {}
): RunResult {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'safenpm-itest-'))

  try {
    // 1. Write capabilities file
    fs.writeFileSync(
      path.join(tmpDir, 'package-capabilities.json'),
      JSON.stringify(capabilities, null, 2),
      'utf8'
    )

    // 2. Copy each fixture into tmpDir/node_modules/<pkgName>/
    //    This is the critical step — it makes the enforcer treat the fixture
    //    as an npm package rather than user application code.
    for (const [pkgName, srcDir] of Object.entries(fixtures)) {
      const pkgDest = path.join(tmpDir, 'node_modules', pkgName)
      fs.mkdirSync(pkgDest, { recursive: true })
      copyDirectory(srcDir, pkgDest)
    }

    // 3. Write test script
    const scriptPath = path.join(tmpDir, 'test-script.js')
    fs.writeFileSync(scriptPath, scriptContent, 'utf8')

    // 4. Run with enforcer loaded via a bootstrap file.
    //
    //    We cannot use NODE_OPTIONS --require with paths that contain spaces
    //    because NODE_OPTIONS splits on spaces and ignores quotes on Windows.
    //    Instead we write a small bootstrap.js to tmpDir (short path, no spaces)
    //    that embeds the real paths as JSON strings and calls require() directly.
    const bootstrapPath = path.join(tmpDir, 'safenpm-bootstrap.js')
    const bootstrapContent = [
      '// Auto-generated by run-with-enforcer.ts — do not edit',
      `require(${JSON.stringify(path.join(PROJECT_NODE_MODULES, 'ts-node'))}).register({`,
      `  project: ${JSON.stringify(TS_CONFIG_PATH)},`,
      `  transpileOnly: true,`,
      `});`,
      `require(${JSON.stringify(ENFORCER_PATH)});`,
    ].join('\n')
    fs.writeFileSync(bootstrapPath, bootstrapContent, 'utf8')

    const result = execSync(`node "${scriptPath}"`, {
      cwd: tmpDir,
      env: {
        ...process.env,
        NODE_OPTIONS: '--require ./safenpm-bootstrap.js',
        ...extraEnv,
      },
      timeout: 15000,
      stdio: 'pipe',
    })

    return { exitCode: 0, stdout: result.toString(), stderr: '' }
  } catch (err: unknown) {
    const e = err as { status?: number; stdout?: Buffer; stderr?: Buffer }
    return {
      exitCode: e.status ?? 1,
      stdout: e.stdout?.toString() ?? '',
      stderr: e.stderr?.toString() ?? '',
    }
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  }
}

/** Recursively copies a directory. */
function copyDirectory(src: string, dest: string): void {
  const entries = fs.readdirSync(src, { withFileTypes: true })
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name)
    const destPath = path.join(dest, entry.name)
    if (entry.isDirectory()) {
      fs.mkdirSync(destPath, { recursive: true })
      copyDirectory(srcPath, destPath)
    } else {
      fs.copyFileSync(srcPath, destPath)
    }
  }
}

// ─── Capability file builders ────────────────────────────────────────────────

/** All-deny profile: no fs, no net, no env, no spawn. */
export function denyAllCapabilities(packageName: string): CapabilitiesFile {
  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    projectRoot: '/test',
    packages: {
      [packageName]: {
        version: '1.0.0',
        fs: { read: [], write: [] },
        net: { outbound: false, hosts: [] },
        env: [],
        child_process: { allowed: false },
        worker_threads: false,
        hasNativeModules: false,
        approvedBy: 'user',
        approvedAt: new Date().toISOString(),
      },
    },
  }
}

/** Profile granting read+write to the OS temp dir and NODE_ENV env var. */
export function tmpAccessCapabilities(packageName: string): CapabilitiesFile {
  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    projectRoot: '/test',
    packages: {
      [packageName]: {
        version: '1.0.0',
        fs: {
          read: [os.tmpdir() + '/**'],
          write: [os.tmpdir() + '/**'],
        },
        net: { outbound: false, hosts: [] },
        env: ['NODE_ENV'],
        child_process: { allowed: false },
        worker_threads: false,
        hasNativeModules: false,
        approvedBy: 'user',
        approvedAt: new Date().toISOString(),
      },
    },
  }
}
